-- SQL Setup for Auld Reekie Coffee Database
-- Copy and run this in Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
  email TEXT PRIMARY KEY,
  username TEXT,
  bio TEXT,
  photo TEXT,
  points INTEGER DEFAULT 0,
  role TEXT DEFAULT 'user',
  status TEXT DEFAULT 'Active',
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
  id TEXT PRIMARY KEY,
  user_email TEXT,
  user_name TEXT,
  menu TEXT,
  items JSONB,
  date TEXT,
  total TEXT,
  status TEXT DEFAULT 'Pending',
  payment_method TEXT DEFAULT 'Cash'
);

-- 3. Complaints Table
CREATE TABLE IF NOT EXISTS public.complaints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT,
  user_name TEXT,
  date TEXT,
  title TEXT,
  status TEXT DEFAULT 'New',
  order_id TEXT
);

-- 4. Menu Catalog Table
CREATE TABLE IF NOT EXISTS public.menu_catalog (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE,
  price NUMERIC,
  category TEXT,
  img TEXT
);

-- 5. Fix RLS: Drop old policies first, then recreate
-- This ensures the policies are correct even if they were previously misconfigured

-- Drop existing policies (ignore errors if they don't exist)
DROP POLICY IF EXISTS "Allow All Profiles" ON profiles;
DROP POLICY IF EXISTS "Allow All Orders" ON orders;
DROP POLICY IF EXISTS "Allow All Complaints" ON complaints;
DROP POLICY IF EXISTS "Allow All Menu" ON menu_catalog;

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_catalog ENABLE ROW LEVEL SECURITY;

-- Create permissive policies for ALL operations (SELECT, INSERT, UPDATE, DELETE)
CREATE POLICY "Allow All Profiles" ON profiles FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Orders" ON orders FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Complaints" ON complaints FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Menu" ON menu_catalog FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- 6. Grant table permissions to anon and authenticated roles
GRANT ALL ON public.profiles TO anon, authenticated;
GRANT ALL ON public.orders TO anon, authenticated;
GRANT ALL ON public.complaints TO anon, authenticated;
GRANT ALL ON public.menu_catalog TO anon, authenticated;

-- Grant sequence usage (needed for auto-increment columns)
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
