-- SQL Template to fix Auld Reekie Coffee Database
-- Copy and run this in Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
  email TEXT PRIMARY KEY,
  username TEXT,
  bio TEXT,
  photo TEXT,
  points INTEGER DEFAULT 0,
  role TEXT DEFAULT 'user',
  status TEXT DEFAULT 'Active',
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
  id TEXT PRIMARY KEY,
  user_email TEXT,
  user_name TEXT,
  menu TEXT,
  items JSONB,
  date TEXT,
  total TEXT,
  status TEXT DEFAULT 'Pending',
  payment_method TEXT DEFAULT 'Cash'
);

-- 3. Complaints Table
CREATE TABLE IF NOT EXISTS public.complaints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT,
  user_name TEXT,
  date TEXT,
  title TEXT,
  status TEXT DEFAULT 'New',
  order_id TEXT
);

-- 4. Menu Catalog Table
CREATE TABLE IF NOT EXISTS public.menu_catalog (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE,
  price NUMERIC,
  category TEXT,
  img TEXT
);

-- 5. Row Level Security (RLS) Configuration
-- We enable RLS and allow all operations for this demo
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_catalog ENABLE ROW LEVEL SECURITY;

-- Dynamic Policies (Safe for development)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow All Profiles') THEN
        CREATE POLICY "Allow All Profiles" ON profiles FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow All Orders') THEN
        CREATE POLICY "Allow All Orders" ON orders FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow All Complaints') THEN
        CREATE POLICY "Allow All Complaints" ON complaints FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow All Menu') THEN
        CREATE POLICY "Allow All Menu" ON menu_catalog FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;
